In [21]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [22]:
data = pd.read_csv('fitness_poses_csvs_out_basic.csv', header=None)
data.head()

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,down (1).jpg,deadlift_down,490.96081,206.47643,-852.63336,502.74338,191.91253,-825.73051,509.09473,191.90467,...,-215.78665,486.73386,669.02515,-130.70737,602.64992,697.67226,-430.89996,430.48889,696.20134,-337.54662
1,down (10).jpg,deadlift_down,663.26691,315.41920,-732.08649,669.07272,303.68370,-721.65405,673.37395,302.28493,...,-116.24514,613.51799,529.89927,-88.36281,718.64693,545.18237,-273.76682,601.73683,546.71492,-235.75686
2,down (11).jpg,deadlift_down,667.79053,316.71048,-633.09589,673.90930,306.28046,-621.92329,678.26744,305.30064,...,-57.38584,614.53255,527.27165,-52.41393,716.81557,547.38007,-187.10304,601.03283,549.29130,-184.79624
3,down (12).jpg,deadlift_down,873.82622,358.94729,-934.96773,882.39861,343.12245,-912.25113,887.27760,341.99296,...,-102.09928,826.31454,663.38329,-80.21163,946.65207,694.72784,-304.97778,807.66472,693.30670,-289.19224
4,down (13).jpg,deadlift_down,880.14931,355.39902,-801.86707,888.29758,340.11990,-784.64035,893.12019,338.87342,...,-96.60158,827.44858,666.66936,-89.97292,941.67374,695.74352,-284.84207,808.94363,695.32741,-281.64139

In [23]:
data.columns = [str(col) for col in data.columns]
data.drop(['0'], axis=1)

,1,2,3,4,5,6,7,8,9,10,...,91,92,93,94,95,96,97,98,99,100
0,deadlift_down,490.96081,206.47643,-852.63336,502.74338,191.91253,-825.73051,509.09473,191.90467,-825.66284,...,-215.78665,486.73386,669.02515,-130.70737,602.64992,697.67226,-430.89996,430.48889,696.20134,-337.54662
1,deadlift_down,663.26691,315.41920,-732.08649,669.07272,303.68370,-721.65405,673.37395,302.28493,-721.62102,...,-116.24514,613.51799,529.89927,-88.36281,718.64693,545.18237,-273.76682,601.73683,546.71492,-235.75686
2,deadlift_down,667.79053,316.71048,-633.09589,673.90930,306.28046,-621.92329,678.26744,305.30064,-621.87996,...,-57.38584,614.53255,527.27165,-52.41393,716.81557,547.38007,-187.10304,601.03283,549.29130,-184.79624
3,deadlift_down,873.82622,358.94729,-934.96773,882.39861,343.12245,-912.25113,887.27760,341.99296,-912.27982,...,-102.09928,826.31454,663.38329,-80.21163,946.65207,694.72784,-304.97778,807.66472,693.30670,-289.19224
4,deadlift_down,880.14931,355.39902,-801.86707,888.29758,340.11990,-784.64035,893.12019,338.87342,-784.66217,...,-96.60158,827.44858,666.66936,-89.97292,941.67374,695.74352,-284.84207,808.94363,695.32741,-281.64139
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,deadlift_up,673.98880,82.14939,-397.29877,680.67146,71.90492,-381.37691,684.81232,72.14215,-381.36608,...,186.03645,609.62654,528.84961,174.34677,719.47067,551.01654,31.55934,609.46972,550.70463,21.63579
120,deadlift_up,674.38057,87.81709,-391.20029,681.13281,77.91795,-375.88383,685.40756,77.79867,-375.87578,...,175.19148,608.71204,531.21600,159.31688,718.76968,551.32926,22.27346,609.83898,552.18697,8.39279
121,deadlift_up,617.09118,62.13902,-381.39313,617.73212,50.71272,-355.51899,619.96147,51.05793,-355.53467,...,451.08536,538.18684,640.92805,30.00699,696.14555,637.90831,330.79540,584.43890,671.58497,-147.98288
122,deadlift_up,917.85286,179.50087,-376.81576,924.81606,168.56081,-358.99136,929.17633,168.25777,-359.00818,...,155.28572,880.81573,644.83635,148.34432,958.78616,673.40248,-5.53855,872.21428,668.52201,-8.12207
123,deadlift_up,631.93623,23.34951,-389.06406,632.01118,10.48031,-363.26874,634.33342,10.49568,-363.30765,...,454.09634,547.54925,617.24084,19.40202,706.99608,616.51497,330.55531,593.31154,649.48970,-159.64121

In [24]:
data['1'].value_counts()

deadlift_up      64
deadlift_down    60
Name: 1, dtype: int64

In [25]:
def newtarget(row):
    if row['1'] == 'deadlift_down':
        return 0
    elif row['1'] == 'deadlift_up':
        return 1

data['1'] = data.apply(newtarget, axis=1)
data['1'].value_counts()

1    64
0    60
Name: 1, dtype: int64

In [26]:
data

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,down (1).jpg,0,490.96081,206.47643,-852.63336,502.74338,191.91253,-825.73051,509.09473,191.90467,...,-215.78665,486.73386,669.02515,-130.70737,602.64992,697.67226,-430.89996,430.48889,696.20134,-337.54662
1,down (10).jpg,0,663.26691,315.41920,-732.08649,669.07272,303.68370,-721.65405,673.37395,302.28493,...,-116.24514,613.51799,529.89927,-88.36281,718.64693,545.18237,-273.76682,601.73683,546.71492,-235.75686
2,down (11).jpg,0,667.79053,316.71048,-633.09589,673.90930,306.28046,-621.92329,678.26744,305.30064,...,-57.38584,614.53255,527.27165,-52.41393,716.81557,547.38007,-187.10304,601.03283,549.29130,-184.79624
3,down (12).jpg,0,873.82622,358.94729,-934.96773,882.39861,343.12245,-912.25113,887.27760,341.99296,...,-102.09928,826.31454,663.38329,-80.21163,946.65207,694.72784,-304.97778,807.66472,693.30670,-289.19224
4,down (13).jpg,0,880.14931,355.39902,-801.86707,888.29758,340.11990,-784.64035,893.12019,338.87342,...,-96.60158,827.44858,666.66936,-89.97292,941.67374,695.74352,-284.84207,808.94363,695.32741,-281.64139
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,up (62).jpg,1,673.98880,82.14939,-397.29877,680.67146,71.90492,-381.37691,684.81232,72.14215,...,186.03645,609.62654,528.84961,174.34677,719.47067,551.01654,31.55934,609.46972,550.70463,21.63579
120,up (63).jpg,1,674.38057,87.81709,-391.20029,681.13281,77.91795,-375.88383,685.40756,77.79867,...,175.19148,608.71204,531.21600,159.31688,718.76968,551.32926,22.27346,609.83898,552.18697,8.39279
121,up (7).jpg,1,617.09118,62.13902,-381.39313,617.73212,50.71272,-355.51899,619.96147,51.05793,...,451.08536,538.18684,640.92805,30.00699,696.14555,637.90831,330.79540,584.43890,671.58497,-147.98288
122,up (8).jpg,1,917.85286,179.50087,-376.81576,924.81606,168.56081,-358.99136,929.17633,168.25777,...,155.28572,880.81573,644.83635,148.34432,958.78616,673.40248,-5.53855,872.21428,668.52201,-8.12207
123,up (9).jpg,1,631.93623,23.34951,-389.06406,632.01118,10.48031,-363.26874,634.33342,10.49568,...,454.09634,547.54925,617.24084,19.40202,706.99608,616.51497,330.55531,593.31154,649.48970,-159.64121

In [27]:
# Preparing the data

X = data.drop(['0','1'], axis=1)
y = data['1']

X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=True, test_size=0.2, random_state=1)

In [28]:
from sklearn.neighbors import KNeighborsClassifier

# Initialize the model and set the hyperparameters
knn = KNeighborsClassifier(n_neighbors=5, weights='distance')

# Train
knn.fit(X_train, y_train)

print("Test data accuracy was", knn.score(X_test, y_test))
print("Train data accuracy was", knn.score(X_train, y_train))

Test data accuracy was 1.0
Train data accuracy was 1.0

In [31]:
knn.predict(X_test)

array([0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1], dtype=int64)